### ISSUE TITLE
Prototypes d'interface

### ISSUE THREAD

**Issue by vfournier11** [SORT-ETS/SORT#30]
- [x] Pen and paper
- [x] Wireframe (après feedback)
- [x] Design
- [x] Implémentation web
- [x] Rétroactions clients
- [ ] Implémentation PI

**Comment by renaudfv** [comment]
Les prototypes Pen&Paper ont été remis. J'attend vos feedback mardi pour commencer l'implémentation web.

**Comment by renaudfv** [comment]
Design de l'interaface mobile pour le cas d'utilisation principal a été réalisé.
Le feature de warning sera ajouté de façon itérative.

**Comment by renaudfv** [comment]
Links to #53 .
I consider this closed as more linked to the design phase and mobile implementation.
