### ISSUE TITLE
Gather facts for differents screens

### ISSUE THREAD

**Issue by vfournier11** [SORT-ETS/SORT#31]

**Comment by renaudfv** [comment]
Will not be done for monday unless we can reach the BDD and get the actual information fast.

**Comment by renaudfv** [comment]
On API side, if Maxim takes hold of Nicolas tasks, its his responsability.

**Comment by DesertMax** [comment]
I've just contacted the BDD, I'm trying to set a meating with person with the steak holder in the beginning of next week. We'll talk about the facts/notes/warnings then.
