### ISSUE TITLE
Add GPU support to Docker

### ISSUE THREAD

**Issue by vfournier11** [SORT-ETS/SORT#35]
To help with training on the TitanX

**Comment by Molinette** [comment]
The Conjure club owns a TitanX and so we can use it to quicken the training process and even the detection tests.

**Comment by DesertMax** [comment]
The Conjure club owns a TitanX and so we can use it to quicken the training process and even the detection tests.

**Comment by vfournier11** [comment]
Docker-nvidia isn't compatible with Windows ...
So we can do it locally. We just need to be able to compile darknet on Windows
