### ISSUE TITLE
Application for the PI

### ISSUE THREAD

**Issue by vfournier11** [SORT-ETS/SORT#53]
- [x] Adjust UI for desktop view
- [x] Dynamic view on results
- [x] Detailled view integration
- [x] Modal view integration
- [x] Button support
- [x] Enter support
- [x] Flash support
- [x] "DPad" support

**Comment by renaudfv** [comment]
Ordered the 40pin GPIO breakout board for RasPI 3.

**Comment by renaudfv** [comment]
@DesertMax I have added you as a contributor to this issue. Please check the task you complete and feel free to add some.
